### ISSUE TITLE
data/proxy.toml missing from git repository

### ISSUE THREAD

**Issue by ERnsTL** [xenith-studios/ataxia#2]
When starting the proxy using ```bin/ataxia-proxy &``` it says, ```missing data/proxy.toml```, which is true - it is not present in the ataxia git repository, only the sister configuration file ```data/ataxia.toml```.

Please add it to the git repository.

**Comment by xenith** [comment]
I have just pushed a new commit which should fix this. Now both the engine and proxy are reading from a single configuration file (`data/ataxia.toml`).
