### ISSUE TITLE
Symbolic links

### ISSUE THREAD

**Issue by Pegrin** [xenith-studios/ataxia#4]
I'm trying to build the project using `cargo build` in Windows OS.
I receive:
```
error: expected item, found `..`
 --> ataxia-core\build.rs:1:1
  |
1 | ../build.rs
  | ^^ expected item

```
It's cuz of using symbolic link I guess. So, using symbolic link might bring some difficulties for non-unix contributors.

**Comment by xenith** [comment]
Thanks for the note! I don't use Windows, so I never have a chance to test that platform. I'll remove the use of the symlink for now. I've been going back and forth on whether that build.rs file should be removed, since it breaks binary reproducibility.
